// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH3K7yYKBr8IbDdvax8YmqKCnS-mPzSgQ',
    appId: '1:527718031865:web:e1161e8237ac43eb525d28',
    messagingSenderId: '527718031865',
    projectId: 'cloneuber-6f1a8',
    authDomain: 'cloneuber-6f1a8.firebaseapp.com',
    databaseURL: 'https://cloneuber-6f1a8-default-rtdb.firebaseio.com',
    storageBucket: 'cloneuber-6f1a8.firebasestorage.app',
    measurementId: 'G-5YPT8LPNNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfg71NveKJfOyoHXRK7VZnCpAKK8HXewg',
    appId: '1:527718031865:android:7ce27af7fff13ed4525d28',
    messagingSenderId: '527718031865',
    projectId: 'cloneuber-6f1a8',
    databaseURL: 'https://cloneuber-6f1a8-default-rtdb.firebaseio.com',
    storageBucket: 'cloneuber-6f1a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwm7wmVtVIvkCVS--UKd08tvMmblQhg9I',
    appId: '1:527718031865:ios:f099b4d8ed23bcd8525d28',
    messagingSenderId: '527718031865',
    projectId: 'cloneuber-6f1a8',
    databaseURL: 'https://cloneuber-6f1a8-default-rtdb.firebaseio.com',
    storageBucket: 'cloneuber-6f1a8.firebasestorage.app',
    iosBundleId: 'com.example.riderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwm7wmVtVIvkCVS--UKd08tvMmblQhg9I',
    appId: '1:527718031865:ios:f099b4d8ed23bcd8525d28',
    messagingSenderId: '527718031865',
    projectId: 'cloneuber-6f1a8',
    databaseURL: 'https://cloneuber-6f1a8-default-rtdb.firebaseio.com',
    storageBucket: 'cloneuber-6f1a8.firebasestorage.app',
    iosBundleId: 'com.example.riderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH3K7yYKBr8IbDdvax8YmqKCnS-mPzSgQ',
    appId: '1:527718031865:web:d6de5523a3578623525d28',
    messagingSenderId: '527718031865',
    projectId: 'cloneuber-6f1a8',
    authDomain: 'cloneuber-6f1a8.firebaseapp.com',
    databaseURL: 'https://cloneuber-6f1a8-default-rtdb.firebaseio.com',
    storageBucket: 'cloneuber-6f1a8.firebasestorage.app',
    measurementId: 'G-H7VXLBJ6H3',
  );
}
